name: "Publish Terraform Module"

inputs:
  path_to_module:
    description: 'Path to the local Terraform module'
    required: true
  module_name:
    description: 'Name of the Terraform module'
    required: true
  module_version:
    description: 'Version of the Terraform module'
    required: true
  tfc_api_token:
    description: 'Terraform Cloud API token'
    required: true

runs: 
  using: "composite"

  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
  
    - name: Authenticate to Terraform Cloud
      shell: bash
      run: echo "Bearer ${{ inputs.tfc_api_token }}" | tr -d '\n' > ~/.terraformrc
      env:
        TERRAFORM_CLI_COLORS: 0
        TERRAFORM_LOG: TRACE

    - name: Terraform init
      shell: bash
      run: terraform init

    - name: Publish Terraform Module
      shell: bash
      run: terraform registry publish ${{ inputs.path_to_module }} ${{ inputs.module_name }}/${{ inputs.module_version }}
